# Optimize preferred component values

Use `e_series()` to define allowed resistor values, then use `optimize()` to rank resistor pairs for a voltage divider. The equations target a divider ratio of 0.33 and an equivalent parallel resistance of 50 Ohm.

In [2]:
from sympy import Eq, symbols

from pyPCBA.lists import e_series
from pyPCBA.values import optimize

In [3]:
# Voltage divider
resistors1 = e_series("E12", "1k", "100k")

R1, R2 = symbols("R1 R2")
eq1 = Eq(R2 / (R1 + R2), 0.33)

solutions = optimize(eq1, resistors1, num_solutions=5)
solutions

   Rank       R1       R2     error
0     1   6800.0   3300.0  0.000098
1     2  68000.0  33000.0  0.000098
2     3   5600.0   2700.0  0.000203
3     4  56000.0  27000.0  0.000203
4     5   8200.0   3900.0  0.000542

In [6]:
# Voltage divider with 50 Ohm output resistance
resistors2 = e_series("E12", "1", "100k")

R1, R2 = symbols("R1 R2")
eqSys1 = [
    Eq(R2 / (R1 + R2), 0.33),
    Eq(R1 * R2 / (R1 + R2), 50),
]

solutions2 = optimize(eqSys1, resistors2, num_solutions=10)
solutions2

   Rank     R1    R2     error
0     1  150.0  68.0  0.007124
1     2  150.0  82.0  0.008690
2     3  180.0  82.0  0.018718
3     4  120.0  68.0  0.026630
4     5  180.0  68.0  0.028765
5     6  120.0  82.0  0.053619
6     7  120.0  56.0  0.057150
7     8  150.0  56.0  0.065084
8     9  220.0  82.0  0.069310
9    10  220.0  68.0  0.082459

In [ ]:
# Same as above, but with our own special operators for voltage divider and parllel connection.
R1, R2 = symbols("R1 R2")

eqSys2 = [
    Eq(R1 | R2, 0.33),
    Eq(R1 // R2, 50),
]

solutions3 = optimize(eqSys2, resistors, num_solutions=10)
solutions3

TypeError: Every item in equations must be a SymPy equality.